spring.sql.init.mode=never
spring.datasource.url=jdbc:postgresql://ep-odd-sun-abajj4fe.eu-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_S6DBTPRKvJ0V

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.kafka.bootstrap-servers=pkc-z3p1v0.europe-west2.gcp.confluent.cloud:9092
spring.kafka.consumer.group-id=SC-76e927e6-1302-4b71-9f73-8a9d8a8e0f4b
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="MPVRUX4QR3QC53FR" password="cfltNr0mqGB0+O6nrvfOsTx78vF/UR5Pi8j4aW3UDae0tl5opgC91bPpRLdXAWNg";


nwr.schedule.kafka.group-id=SC-7336bcc5-349a-41bd-9421-de24273d4a52
nwr.schedule.kafka.topic=prod-1010-Darwin-Train-Information-Push-Port-IIII2_0-JSON


networkrail.cramlington.stanox=12136
networkrail.cramlington.tiploc=CRMLNGT
networkrail.cramlington.crs=CRM


